version: '3.8'
services:
    redis:
        image: redis:5.0-alpine
        container_name: redis_server
        ports:
          - 6379:6379
        restart: unless-stopped

    api-server:
        restart: always
        build: .
        container_name: api-server
        ports:
            - 8000:8000
        env_file:
            - common.env
        volumes:
            - ./:/app
        depends_on:
            - redis